### ISSUE TITLE
Portal + BottomSheet release crash

### ISSUE THREAD

**Issue by sergeylaptev** [gorhom/react-native-portal#12]
```
  "@gorhom/bottom-sheet": "3.3.1",
  "@gorhom/portal": "1.0.2",
```

If I use 1.0.2 version of portal library, and wrap my BottomSheet into `<Portal host="...">...</Portal>` everything works fine in debug configuration on iOS. BUT when I try a release build it crashes as soon as I render `<Portal />` part. If I render non bottom-sheet related components inside portal, they render fine and no errors occur.

![image](https://user-images.githubusercontent.com/5740795/109288028-664f3980-7835-11eb-8c0d-c3988c910baf.png)

I've downgraded to 0.2.0 version of the library and it seems to be working fine. Is it somehow related to `immer`?

**Comment by gorhom** [comment]
Bottom Sheet uses v0.2 portal, not v1. I will migrate it to v1 later next week

**Comment by sergeylaptev** [comment]
Makes sense:) Is it possible to reuse same PortalHost for several portals in 0.2.0?

**Comment by gorhom** [comment]
Yes, you can! This is how i used it with bottom sheet stack modals
