### ISSUE TITLE
Portal does not render when unmounting `PortalHost` and remounting again

### ISSUE THREAD

**Issue by mrousavy** [gorhom/react-native-portal#18]
Awesome library @gorhom! 

In my use-case, I conditionally render a `<PortalHost>`. This works on the first time, but after unmounting it and mounting it again, the Portal inside does not render anymore.

I'd love to provide a reproduceable example, but unfortunately the codebase is very nested and WIP right now, if you have trouble reproducing this I could try patching something together..

Thanks!

**Comment by gorhom** [comment]
Hey @mrousavy , i will look into it 👍

**Comment by gorhom** [comment]
should be fixed with `v1.0.8`

**Comment by roviks** [comment]
@gorhom  still not fixed

**Comment by tolypash** [comment]
Experiencing same issue

**Comment by gregoryalary** [comment]
Same here with `1.0.14`. ☹️
