### ISSUE TITLE
External Portals don't work inside BottomSheetModals

### ISSUE THREAD

**Issue by a8t** [gorhom/react-native-portal#2]
Hi, thanks for your hard work. I'm on 2.0.3, with Expo SDK 40.

Consider the following:

```jsx
<ExternalProvider>
    <BottomSheetModalProvider>
        <App/>
    </BottomSheetModalProvider>
</ExternalProvider>
```

inside `<App/>`:

```jsx
const App = () => {
    return (
        <BottomSheetModal>
            <OtherStuff/>
        </BottomSheetModal/>
    )
}

const OtherStuff = () => {
    const externalllyProvidedStuff = useExternalContext()
    return <EvenMoreStuff/>
}
```

`externallyProvidedStuff` is coming up as null when it shouldn't. It's happening for React Navigation as well as our own custom context hooks, which worked with other libraries.

I am wondering if this is something particular to your `Portal` library. We wrote something similar last year, actually, and abandoned it for this problem.

Have you heard this from any other users?

**Comment by gorhom** [comment]
thanks @a8t for submitting this issue , i will investigate it

**Comment by gorhom** [comment]
hi @a8t , could you provide a very simple reproducible sample code using BottomSheetModal, or simple Portal implementation ?

**Comment by a8t** [comment]
Oh shoot, I meant to make this issue in the bottom sheet modal repo, not this one. I didn't mean to imply that it's related to your portal implementation necessarily. Yes I will try to do that asap

**Comment by gorhom** [comment]
No no , I actually moved it here 😅

**Comment by gorhom** [comment]
Since it is related to the portal and handling external contexts , i thought it would be best to solve it here

**Comment by thealiilman** [comment]
Hey @gorhom! 👋  First of all, thank you for your contributions to OSS, the packages you have built are awesome.

Now, I think I'm running into an issue similar to @a8t's.

I'm using formik's `<Formik />` and your bottom sheet's `<BottomSheetModal />`. My bottom sheet modal is wrapped by `<Formik />`. Inside my bottom sheet modal, I have a formik `<Field />`.
For some reason, the `<Field />` within my bottom sheet modal is running into errors, saying _getFieldProps is not a function_. The logs also say that there isn't a formik context present for the `<Field />` to use. Here are some screenshots for more info.

<details>
<summary>Screenshots</summary>
<img width="315" alt="Screenshot 2021-03-10 at 19 59 12" src="https://user-images.githubusercontent.com/26957580/110626047-3449ba00-81db-11eb-94fb-5c6ec3fb4e65.png">
<img width="319" alt="Screenshot 2021-03-10 at 19 59 18" src="https://user-images.githubusercontent.com/26957580/110626068-39a70480-81db-11eb-874e-c35d6cd38282.png">
<img width="320" alt="Screenshot 2021-03-10 at 19 59 25" src="https://user-images.githubusercontent.com/26957580/110626086-40ce1280-81db-11eb-94eb-dab0dbaf2b12.png">
</details>


This is a snack I created to demonstrate the issue.
https://snack.expo.io/@aliilman-surialabs/formik-and-react-native-portal

I may be wrong, but I believe the poral is causing the Formik context to be unavailable for any `<Field />` nested within `<BottomSheetModal />`.

**Comment by gorhom** [comment]
hi @thealiilman, 

the problem is your modal will be teleported to the provider node, which means `Field` won't be able to access `Formik` provider functionalities.

```tsx
    <BottomSheetModalProvider>
      <View style={{ paddingVertical: 32, flexGrow: 1, justifyContent: 'center' }}>
        <Text>Rock n roll!</Text>
        <Formik onSubmit={onSubmit} initialValues={{ name: '' }}>
          {({ handleSubmit }) => (
            <>
              <Field name="name">
                {({ field: { name, onChange, value } }) => (
                  <TextInput value={value} onChangeText={onChange(name)} placeholder="Enter here" />
                )}
              </Field>
              <BottomSheetModal ref={bottomSheetRef} snapPoints={['95%']}>
                <Field name="bio">
                  {({ field: { name, onChange, value } }) => (
                    <TextInput value={value} onChangeText={onChange(name)} placeholder="Enter here" />
                  )}
                </Field>
              </BottomSheetModal>
              <TouchableOpacity activeOpacity={0.8} onPress={handleSubmit}>
                <Text>Submit!</Text>
              </TouchableOpacity>
              <TouchableOpacity activeOpacity={0.8} onPress={() => bottomSheetRef?.current?.present()}>
                <Text>Open bottom sheet</Text>
              </TouchableOpacity>
            </>
          )}
        </Formik>
      </View>
      {/* YOUR MODAL WILL BE TELEPORTED HERE */}
    </BottomSheetModalProvider>
```

**Comment by thealiilman** [comment]
> hi @thealiilman, 
> 
> 
> 
> the problem is your modal will be teleported to the provider node, which means `Field` won't be able to access `Formik` provider functionalities.
> 
> 
> 
> ```tsx
> 
>     <BottomSheetModalProvider>
> 
>       <View style={{ paddingVertical: 32, flexGrow: 1, justifyContent: 'center' }}>
> 
>         <Text>Rock n roll!</Text>
> 
>         <Formik onSubmit={onSubmit} initialValues={{ name: '' }}>
> 
>           {({ handleSubmit }) => (
> 
>             <>
> 
>               <Field name="name">
> 
>                 {({ field: { name, onChange, value } }) => (
> 
>                   <TextInput value={value} onChangeText={onChange(name)} placeholder="Enter here" />
> 
>                 )}
> 
>               </Field>
> 
>               <BottomSheetModal ref={bottomSheetRef} snapPoints={['95%']}>
> 
>                 <Field name="bio">
> 
>                   {({ field: { name, onChange, value } }) => (
> 
>                     <TextInput value={value} onChangeText={onChange(name)} placeholder="Enter here" />
> 
>                   )}
> 
>                 </Field>
> 
>               </BottomSheetModal>
> 
>               <TouchableOpacity activeOpacity={0.8} onPress={handleSubmit}>
> 
>                 <Text>Submit!</Text>
> 
>               </TouchableOpacity>
> 
>               <TouchableOpacity activeOpacity={0.8} onPress={() => bottomSheetRef?.current?.present()}>
> 
>                 <Text>Open bottom sheet</Text>
> 
>               </TouchableOpacity>
> 
>             </>
> 
>           )}
> 
>         </Formik>
> 
>       </View>
> 
>       {/* YOUR MODAL WILL BE TELEPORTED HERE */}
> 
>     </BottomSheetModalProvider>
> 
> ```

Ha, that explains it! My lack of experience with using portals is obvious. 🙂 Appreciate the quick response @gorhom.

**Comment by gorhom** [comment]
@thealiilman no problem :)
