### ISSUE TITLE
External contexts don't work inside modal bottom sheet

### ISSUE THREAD

**Issue by a8t** [gorhom/react-native-portal#3]
Hi, thanks for your hard work. I'm on 2.0.3, with Expo SDK 40.

Consider the following:

```jsx
<ExternalProvider>
    <BottomSheetModalProvider>
        <App/>
    </BottomSheetModalProvider>
</ExternalProvider>
```

inside `<App/>`:

```jsx
const App = () => {
    const externallyProvidedStuff = useExternalContext() 

    return <OtherStuff/>
}
```

`externallyProvidedStuff` is coming up as null. It's happening for React Navigation as well as our own custom context hooks, which worked with other libraries.

I am wondering if this is something particular to your `Portal` library. We wrote something similar last year, actually, and abandoned it for this problem.

Have you heard this from any other users?

**Comment by gorhom** [comment]
hi @a8t , i have tested your use-case and it seems working fine , i would advice to try it out on a bare project and see if it works

**Comment by zhigang1992** [comment]
I think the example here should be

```
<BottomSheetModalProvider>
    <ExternalProvider>
        <App/>
    </ExternalProvider>
</BottomSheetModalProvider>
```

where Portal context is maybe at the root of the app.

**Comment by gorhom** [comment]
hi @zhigang1992 , easy way to avoid this issue is by using `PortalHost` and keeping it in your custom providers:

```tsx
const App = () => {
  return (
    <PortalProvider>
      <CustomProvider>
        <Navigator />
        <PortalHost name="custom_host" />
      </CustomProvider>
    </PortalProvider>
  )
}
```

**Comment by henryornellas** [comment]
I looked at [#2](https://github.com/gorhom/react-native-portal/issues/2) and this one, and still can't really understand it.
My case is same as [this](https://github.com/gorhom/react-native-portal/issues/2#issuecomment-795316923) but with React Hook Form.

```ts
<Form>
  <BottomSheetModal>
    <FormField /> // not working because empty form context
  </BottomSheetModal>
</Form>
```

_layout.tsx
```ts
import { PortalHost } from "@rn-primitives/portal";

return (
  <GestureHandlerRootView style={{ flex: 1 }}>
    <BottomSheetModalProvider>
      <QueryClientProvider client={queryClient}>
        <Stack />

        <PortalHost />
      </QueryClientProvider>
    </BottomSheetModalProvider>
  </GestureHandlerRootView>
)
```

What should I do?
