### ISSUE TITLE
Can not mock <Portal /> using Jest and react-test-renderer

### ISSUE THREAD

**Issue by lmasneri** [gorhom/react-native-portal#38]
I would like to Mock using jest the component <Portal /> from @gorhom/portal as a View.

I would like to do it because the <Portal /> component require a <PortalProvider /> at the root of the app. But I would like to test a single screen.

This is the mock that I've done:

```
import { jest } from '@jest/globals'

jest.mock('@gorhom/portal', () => {
  const react = require('react-native')

  return {
    __esModule: true,
    Portal: () => react.View,
    usePortal: jest.fn(),
  }
})

```

But when I call in my test my screen this is the error I have:

```
'PortalDispatchContext' cannot be null, please add 'PortalProvider' to the root component.

       7 |
       8 | test('renders correctly', () => {
    >  9 |   const tree = renderer.create(<CreateAccount />).toJSON()
         |                         ^
      10 |   expect(tree).toMatchSnapshot()
      11 | })
      12 |
```

And the component causing this issue is this one:

```
const Modal = () => {

  ...

  return (
    <Portal>
      <BottomSheet>
        {...}
      </BottomSheet>
    </Portal>
  )
}
```

If you have any idea (this is the so post related: https://stackoverflow.com/questions/75286623/set-portal-from-gorhom-portal-as-view-using-mock-in-jest)

**Comment by lmasneri** [comment]
@gorhom any idea ?

**Comment by BruceSuperProgramer** [comment]
Any solution so far?

**Comment by BruceSuperProgramer** [comment]
This working for me

jest.mock('@gorhom/portal', () => {
  const reactNative = jest.requireActual('react-native');
  const {View} = reactNative;
  return {
    __esModule: true,
    Portal: ({children}: {children: JSX.Element}) => <View>{children}</View>,
    usePortal: jest.fn(),
  };
});
