### ISSUE TITLE
Immer "enableES5" issue

### ISSUE THREAD

**Issue by sergeylaptev** [gorhom/react-native-portal#9]
![image](https://user-images.githubusercontent.com/5740795/108859255-163a6200-75fe-11eb-86dd-d89adc3c3e7b.png)

Hello and thanks for the solid library. Installed latest version 1.0.0. Everything works fine on iOS, android complains about immer es5 fallback usage. I guess need to call the respective method inside the library. https://immerjs.github.io/immer/docs/installation#pick-your-immer-version

**Comment by sergeylaptev** [comment]
Adding "enableES5" right before "produce" invocation fixes the issue
![image](https://user-images.githubusercontent.com/5740795/108860836-a4fbae80-75ff-11eb-91a2-96c770a10031.png)

**Comment by gorhom** [comment]
thanks @sergeylaptev for submitting this issue and investigate it , i will create a pr later today 👍

**Comment by sergeylaptev** [comment]
Thank you

**Comment by gorhom** [comment]
fixed with `v1.0.1`  🎉

**Comment by sergeylaptev** [comment]
Waiting for the npm release:)

**Comment by gorhom** [comment]
i just published `v1.0.2` on npm 😅
